# Basic
title: tgjarwl的博客
subtitle: 道可道，非常道；名可名，非常名
description: 记录生活，记录更好的自己。
# 头像里面的标题
avatarTitle: tgjarwl
# 头像里面的描述
avatarDesc: 逆向 / 编程
url: "https://tgjarwl.github.io"

#gitment
# comment_gitment_repo: https://github.com/tgjarwl/tgjarwl.github.io
# comment_gitment_clientId: 
# comment_gitment_clientSecret: 

valine_comment:
  enable: true
# app_id
  leancloud_appid: hQKGaeJIS6EKerqSsoCUX0E7-tgjarwl
# app_key
  leancloud_appkey: MjNOS6VGmaY29xsCptgjarwl
# placeholde
  placeholder: "欢迎提出您的宝贵意见"

# Social
social:
    github: tgjarwl
    twitter: tgjarwl
    mail: tgjarwl@outlook.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#    id:    


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/tgjarwl/tgjarwl.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 工具, description: tools, url: '/tools'}
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
